branch-defaults:
  main:
    environment: super-scraper-env
    group_suffix: null
global:
  application_name: superScraper
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: root-temp
  repository: null
  sc: git
  workspace_type: Application
